name: example
description: Example of flutter center text.
publish_to: "none"
version: 1.0.0+1

environment: {sdk: ">=3.3.4 <4.0.0"}

dependencies:
  flutter: {sdk: flutter}
  center_text: {path: ../}

dev_dependencies:
  flutter_lints: ^3.0.0
