name: center_text
description: >
  A placeholder for better Flutter development experience,
  that you don't need to make all children required.
version: 0.0.0
repository: https://github.com/aprosail/center-text
environment: {sdk: ">=3.3.4 <4.0.0", flutter: ">=3.19.6"}

dependencies:
  flutter: {sdk: flutter}
  wrap: ^0.2.0

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^3.0.0
